//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sber-bank.database.windows.net;Initial Catalog=SberBankDb;Integrated " +
            "Security=False;User ID=Yura;Password=Train2brain4;Connect Timeout=60;Encrypt=Fal" +
            "se;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=F" +
            "alse")]
        public string SberBankCS {
            get {
                return ((string)(this["SberBankCS"]));
            }
            set {
                this["SberBankCS"] = value;
            }
        }
    }
}
